### PR TITLE
added support for multiple commands in a single comment

### PR DESCRIPTION
**Pull request by The-Nutty**
For example "!team Astralis !team CLG" would return the details for both teams ina a single comment. (works if you mix teams and players as well).

It works by getting the number of calls in a comment and get_team now takes a new parameter the call number (in the example above 0  would return Astralis 1 CLG), and rather than posting the reply straight away it adds the contents of the would be comment to comment_reply and actually posts that after all players and teams have been added.

Note that i dont have a DB to hand to test this with but im confident it will work fine. If somebody could point me in the direction of how to set up the correct db as well as the environment variables that would be useful.

### CODE REVIEW

**Comment by The-Nutty** [comment]
There that should be fixed now

**Comment by Charrod** [comment]
If you can place it inside the for-loop, I will merge the request! (approx line 308)

**Comment by The-Nutty** [comment]
Good spot, fixed

**Comment by The-Nutty** [comment]
Umm its working fine for me, see http://www.reddit.com/r/globaloffensive/comments/44kwzm/enjoy_the_overwatch/czs3kry

**Comment by Charrod** [comment]
It works for 2 players or 2 teams, but not for a match of both it seems

**Comment by Charrod** [comment]
Also it is running significantly slower. Any idea where the delay is coming from?

**Comment by The-Nutty** [comment]
Yeah, I have some ideas for performance improvements also why not use python 3 that will speed it up significantly

**Comment by The-Nutty** [comment]
also its working fine for me mixing teams and players: https://www.reddit.com/r/GlobalOffensive/comments/44kwzm/enjoy_the_overwatch/czsf2v0

**Comment by Charrod** [comment]
Yeah, I pushed a fix for the mix of teams and players. In general, Python 3.x is slightly slower than its 2.x counterpart. Python 3 is primarily a restructuring of the language, but not really performance focused.

**Pull request merged**
