### PR TITLE
added extra paramiters to get_team and get_count so that it only retu…

### PR DESCRIPTION
**Pull request by The-Nutty**
…rns a count for eather a team or player not both, redusing run time

This should speed it up a bit, now you specify weather you want a count for a team or player. previously it always returned the total.

### CODE REVIEW

**Comment by The-Nutty** [comment]
Ok sure, my logic was that it would quite significantly reduce load on the database and database calls. Because it wont process everything twice. But ok

**Comment by Charrod** [comment]
As far as I can tell, the database will be called the same amount of times

**Comment by TomHazellCov** [comment]
No because currently it iterates through the list for players and teams twice once finding teams one finding players (each time hitting the dB...). With this it will iterate through just the player calls trying to find players and just the team calls trying to find teams

**Comment by The-Nutty** [comment]
No because currently it iterates through the list for players and teams twice once finding teams one finding players (each time hitting the dB...). With this it will iterate through just the player calls trying to find players and just the team calls trying to find teams

**Pull request closed without merging**
